/**
 * DATA DUMMY LENGKAP — Bahasa Indonesia
 * Digunakan di Fase 1 sebelum database terhubung
 */

// ============ KATEGORI ============
export const dummyCategories = {
  service: [
    { id: "cat-1", name: "Fotokopi & Print", slug: "fotokopi-print", kind: "service", sortOrder: 1 },
    { id: "cat-2", name: "Cetak Foto & Banner", slug: "cetak-foto-banner", kind: "service", sortOrder: 2 },
    { id: "cat-3", name: "Jilid & Laminating", slug: "jilid-laminating", kind: "service", sortOrder: 3 },
    { id: "cat-4", name: "Scan & Digitalisasi", slug: "scan-digitalisasi", kind: "service", sortOrder: 4 },
    { id: "cat-5", name: "Layanan Lainnya", slug: "layanan-lainnya", kind: "service", sortOrder: 5 },
  ],
  product: [
    { id: "cat-p1", name: "Alat Tulis", slug: "alat-tulis", kind: "product", sortOrder: 1 },
    { id: "cat-p2", name: "Kertas & Buku", slug: "kertas-buku", kind: "product", sortOrder: 2 },
    { id: "cat-p3", name: "Amplop & Map", slug: "amplop-map", kind: "product", sortOrder: 3 },
    { id: "cat-p4", name: "Tinta & Spidol", slug: "tinta-spidol", kind: "product", sortOrder: 4 },
  ],
};

// ============ LAYANAN ============
export const dummyServices = [
  {
    id: "svc-1",
    categoryId: "cat-1",
    categoryName: "Fotokopi & Print",
    categorySlug: "fotokopi-print",
    name: "Fotokopi Dokumen",
    slug: "fotokopi-dokumen",
    shortDescription: "Fotokopi cepat dan rapi untuk berbagai ukuran kertas.",
    description: "Layanan fotokopi hitam putih dengan kertas HVS 70gr berkualitas. Cocok untuk fotokopi KTP, ijazah, dokumen kantor, soal ujian, dan berbagai keperluan sehari-hari. Mesin kami menghasilkan salinan yang tajam dan jelas.",
    unit: "lembar",
    basePrice: 300,
    imageUrl: null,
    sortOrder: 1,
    isActive: true,
    isBulkDiscountEligible: true,
    variants: [
      { id: "sv-1-1", label: "A4 HVS 70gr — Hitam Putih", price: 300, attributes: { ukuran: "A4", warna: "hitam-putih", kertas: "HVS 70gr" }, sortOrder: 1 },
      { id: "sv-1-2", label: "A4 HVS 70gr — Bolak-Balik", price: 550, attributes: { ukuran: "A4", warna: "hitam-putih", sisi: "bolak-balik" }, sortOrder: 2 },
      { id: "sv-1-3", label: "F4 HVS 70gr — Hitam Putih", price: 350, attributes: { ukuran: "F4", warna: "hitam-putih", kertas: "HVS 70gr" }, sortOrder: 3 },
      { id: "sv-1-4", label: "A3 — Hitam Putih", price: 700, attributes: { ukuran: "A3", warna: "hitam-putih" }, sortOrder: 4 },
    ],
    useCases: [
      "Fotokopi KTP & kartu identitas",
      "Penggandaan dokumen kantor & skripsi",
      "Fotokopi soal ujian & handout",
      "Salinan akta, sertifikat, & ijazah",
    ],
  },
  {
    id: "svc-2",
    categoryId: "cat-1",
    categoryName: "Fotokopi & Print",
    categorySlug: "fotokopi-print",
    name: "Print Dokumen",
    slug: "print-dokumen",
    shortDescription: "Print dokumen Word, PDF, Excel, dan PowerPoint.",
    description: "Layanan cetak dokumen dari file digital Anda. Kirim file via WhatsApp, email, atau bawa flash disk. Kami mencetak dengan presisi warna akurat dan teks tajam. Tersedia pilihan hitam putih dan warna.",
    unit: "lembar",
    basePrice: 500,
    imageUrl: null,
    sortOrder: 2,
    isActive: true,
    isBulkDiscountEligible: true,
    variants: [
      { id: "sv-2-1", label: "A4 HVS 70gr — Hitam Putih", price: 500, attributes: { ukuran: "A4", warna: "hitam-putih" }, sortOrder: 1 },
      { id: "sv-2-2", label: "A4 HVS 70gr — Warna", price: 2000, attributes: { ukuran: "A4", warna: "warna" }, sortOrder: 2 },
      { id: "sv-2-3", label: "A4 HVS 70gr — Warna Bolak-Balik", price: 3500, attributes: { ukuran: "A4", warna: "warna", sisi: "bolak-balik" }, sortOrder: 3 },
      { id: "sv-2-4", label: "F4 HVS 70gr — Hitam Putih", price: 600, attributes: { ukuran: "F4", warna: "hitam-putih" }, sortOrder: 4 },
      { id: "sv-2-5", label: "F4 HVS 70gr — Warna", price: 2500, attributes: { ukuran: "F4", warna: "warna" }, sortOrder: 5 },
      { id: "sv-2-6", label: "A3 — Hitam Putih", price: 1000, attributes: { ukuran: "A3", warna: "hitam-putih" }, sortOrder: 6 },
      { id: "sv-2-7", label: "A3 — Warna", price: 4000, attributes: { ukuran: "A3", warna: "warna" }, sortOrder: 7 },
    ],
    useCases: [
      "Cetak laporan & proposal bisnis",
      "Print tugas kuliah & skripsi",
      "Cetak presentasi PowerPoint",
      "Print formulir & dokumen resmi",
    ],
  },
  {
    id: "svc-3",
    categoryId: "cat-2",
    categoryName: "Cetak Foto & Banner",
    categorySlug: "cetak-foto-banner",
    name: "Cetak Foto",
    slug: "cetak-foto",
    shortDescription: "Cetak foto berkualitas tinggi dengan kertas glossy.",
    description: "Layanan cetak foto dengan kertas foto glossy dan matte premium. Hasil cetak tahan lama dengan warna cerah dan detail tajam. Tersedia berbagai ukuran dari 2R hingga 12R.",
    unit: "lembar",
    basePrice: 3500,
    imageUrl: null,
    sortOrder: 3,
    isActive: true,
    isBulkDiscountEligible: false,
    variants: [
      { id: "sv-3-1", label: "2R (6×9 cm) — Glossy", price: 2000, attributes: { ukuran: "2R", jenis: "glossy" }, sortOrder: 1 },
      { id: "sv-3-2", label: "3R (8.9×12.7 cm) — Glossy", price: 2500, attributes: { ukuran: "3R", jenis: "glossy" }, sortOrder: 2 },
      { id: "sv-3-3", label: "4R (10×15 cm) — Glossy", price: 3500, attributes: { ukuran: "4R", jenis: "glossy" }, sortOrder: 3 },
      { id: "sv-3-4", label: "4R (10×15 cm) — Matte", price: 4000, attributes: { ukuran: "4R", jenis: "matte" }, sortOrder: 4 },
      { id: "sv-3-5", label: "5R (12.7×17.8 cm) — Glossy", price: 5000, attributes: { ukuran: "5R", jenis: "glossy" }, sortOrder: 5 },
      { id: "sv-3-6", label: "6R (15×20 cm) — Glossy", price: 7000, attributes: { ukuran: "6R", jenis: "glossy" }, sortOrder: 6 },
      { id: "sv-3-7", label: "10R (25.4×30.5 cm) — Glossy", price: 20000, attributes: { ukuran: "10R", jenis: "glossy" }, sortOrder: 7 },
      { id: "sv-3-8", label: "12R (30.5×38 cm) — Glossy", price: 35000, attributes: { ukuran: "12R", jenis: "glossy" }, sortOrder: 8 },
    ],
    useCases: [
      "Foto wisuda & kenangan keluarga",
      "Foto pas untuk lamaran kerja",
      "Cetak foto liburan",
      "Kado foto untuk orang tersayang",
    ],
  },
  {
    id: "svc-4",
    categoryId: "cat-2",
    categoryName: "Cetak Foto & Banner",
    categorySlug: "cetak-foto-banner",
    name: "Cetak Banner & Spanduk",
    slug: "cetak-banner",
    shortDescription: "Cetak banner flexi indoor/outdoor ukuran custom.",
    description: "Cetak banner dan spanduk dengan bahan flexi 280gr (indoor) dan 340gr (outdoor) berkualitas tinggi. Cocok untuk promosi, acara, spanduk kantor, banner event, dan kebutuhan display lainnya. Harga dihitung per meter persegi.",
    unit: "m²",
    basePrice: 25000,
    imageUrl: null,
    sortOrder: 4,
    isActive: true,
    isBulkDiscountEligible: false,
    isBannerService: true,
    variants: [
      { id: "sv-4-1", label: "Flexi 280gr — Indoor (Rp/m²)", price: 25000, attributes: { bahan: "flexi-280gr", penggunaan: "indoor" }, sortOrder: 1 },
      { id: "sv-4-2", label: "Flexi 340gr — Outdoor (Rp/m²)", price: 35000, attributes: { bahan: "flexi-340gr", penggunaan: "outdoor" }, sortOrder: 2 },
      { id: "sv-4-3", label: "Vinyl Premium — Indoor (Rp/m²)", price: 45000, attributes: { bahan: "vinyl-premium", penggunaan: "indoor" }, sortOrder: 3 },
    ],
    useCases: [
      "Banner promosi toko & bisnis",
      "Spanduk acara & seminar",
      "Banner ulang tahun & wedding",
      "Display produk & pameran",
    ],
  },
  {
    id: "svc-5",
    categoryId: "cat-3",
    categoryName: "Jilid & Laminating",
    categorySlug: "jilid-laminating",
    name: "Jilid Dokumen",
    slug: "jilid-dokumen",
    shortDescription: "Jilid spiral, softcover, dan hardcover untuk laporan & skripsi.",
    description: "Layanan penjilidan profesional untuk laporan, skripsi, proposal, dan dokumen tebal lainnya. Tersedia jilid spiral kawat, jilid softcover warna, dan jilid hardcover hard panas.",
    unit: "buku",
    basePrice: 15000,
    imageUrl: null,
    sortOrder: 5,
    isActive: true,
    isBulkDiscountEligible: false,
    variants: [
      { id: "sv-5-1", label: "Jilid Spiral A4 (≤100 lembar)", price: 15000, attributes: { jenis: "spiral", ukuran: "A4", maks: "100 lembar" }, sortOrder: 1 },
      { id: "sv-5-2", label: "Jilid Spiral A4 (101–200 lembar)", price: 20000, attributes: { jenis: "spiral", ukuran: "A4", maks: "200 lembar" }, sortOrder: 2 },
      { id: "sv-5-3", label: "Jilid Spiral F4 (≤100 lembar)", price: 17000, attributes: { jenis: "spiral", ukuran: "F4", maks: "100 lembar" }, sortOrder: 3 },
      { id: "sv-5-4", label: "Jilid Softcover A4 — Warna", price: 25000, attributes: { jenis: "softcover", ukuran: "A4", cover: "warna" }, sortOrder: 4 },
      { id: "sv-5-5", label: "Jilid Hardcover A4 — Panas", price: 50000, attributes: { jenis: "hardcover", ukuran: "A4", metode: "panas" }, sortOrder: 5 },
    ],
    useCases: [
      "Jilid skripsi & laporan magang",
      "Jilid proposal bisnis",
      "Jilid modul & diktat kuliah",
      "Jilid laporan PKL & KKN",
    ],
  },
  {
    id: "svc-6",
    categoryId: "cat-3",
    categoryName: "Jilid & Laminating",
    categorySlug: "jilid-laminating",
    name: "Laminating",
    slug: "laminating",
    shortDescription: "Laminating glossy & doff untuk kartu, sertifikat, dan dokumen penting.",
    description: "Layanan laminating dengan plastik berkualitas untuk melindungi dokumen penting dari kerusakan, air, dan debu. Tersedia pilihan glossy (mengkilap) dan doff (matte).",
    unit: "lembar",
    basePrice: 5000,
    imageUrl: null,
    sortOrder: 6,
    isActive: true,
    isBulkDiscountEligible: false,
    variants: [
      { id: "sv-6-1", label: "A4 — Glossy", price: 5000, attributes: { ukuran: "A4", jenis: "glossy" }, sortOrder: 1 },
      { id: "sv-6-2", label: "A4 — Doff (Matte)", price: 6000, attributes: { ukuran: "A4", jenis: "doff" }, sortOrder: 2 },
      { id: "sv-6-3", label: "F4 — Glossy", price: 6000, attributes: { ukuran: "F4", jenis: "glossy" }, sortOrder: 3 },
      { id: "sv-6-4", label: "A3 — Glossy", price: 10000, attributes: { ukuran: "A3", jenis: "glossy" }, sortOrder: 4 },
      { id: "sv-6-5", label: "ID Card / Kartu (per sisi)", price: 3000, attributes: { ukuran: "ID Card", jenis: "glossy" }, sortOrder: 5 },
    ],
    useCases: [
      "Laminating sertifikat & ijazah",
      "Laminating kartu nama & ID card",
      "Laminating menu restoran",
      "Laminating foto kenangan",
    ],
  },
  {
    id: "svc-7",
    categoryId: "cat-4",
    categoryName: "Scan & Digitalisasi",
    categorySlug: "scan-digitalisasi",
    name: "Scan Dokumen",
    slug: "scan-dokumen",
    shortDescription: "Scan dokumen ke PDF atau JPG dengan hasil bersih dan tajam.",
    description: "Layanan scanning dokumen ke format digital (PDF, JPG, atau PNG). Hasil scan bersih, resolusi tinggi (300–600 DPI), siap kirim via WhatsApp atau email. Cocok untuk digitalisasi arsip, KTP, ijazah, dan kontrak.",
    unit: "lembar",
    basePrice: 1000,
    imageUrl: null,
    sortOrder: 7,
    isActive: true,
    isBulkDiscountEligible: false,
    variants: [
      { id: "sv-7-1", label: "A4 ke PDF — per lembar", price: 1000, attributes: { ukuran: "A4", format: "PDF" }, sortOrder: 1 },
      { id: "sv-7-2", label: "A4 ke JPG — per lembar", price: 1000, attributes: { ukuran: "A4", format: "JPG" }, sortOrder: 2 },
      { id: "sv-7-3", label: "F4 ke PDF — per lembar", price: 1500, attributes: { ukuran: "F4", format: "PDF" }, sortOrder: 3 },
      { id: "sv-7-4", label: "A3 ke PDF — per lembar", price: 2000, attributes: { ukuran: "A3", format: "PDF" }, sortOrder: 4 },
      { id: "sv-7-5", label: "Buku/Majalah (per halaman)", price: 1500, attributes: { jenis: "buku", format: "PDF" }, sortOrder: 5 },
    ],
    useCases: [
      "Scan KTP & dokumen identitas",
      "Digitalisasi arsip kantor lama",
      "Scan kontrak & surat perjanjian",
      "Scan buku & materi kuliah",
    ],
  },
  {
    id: "svc-8",
    categoryId: "cat-2",
    categoryName: "Cetak Foto & Banner",
    categorySlug: "cetak-foto-banner",
    name: "Cetak Undangan & Brosur",
    slug: "cetak-undangan-brosur",
    shortDescription: "Cetak undangan pernikahan, ulang tahun, dan brosur promosi.",
    description: "Layanan cetak undangan dan brosur dengan kertas art paper 210gr berkualitas premium. Warna cerah, detail tajam, dan finishing rapi. Harga mulai dari Rp 2.000 per lembar untuk brosur lipat tiga.",
    unit: "lembar",
    basePrice: 2000,
    imageUrl: null,
    sortOrder: 8,
    isActive: true,
    isBulkDiscountEligible: false,
    variants: [
      { id: "sv-8-1", label: "Brosur A4 Lipat 3 — Art Paper 210gr", price: 2000, attributes: { jenis: "brosur", ukuran: "A4", kertas: "art paper 210gr" }, sortOrder: 1 },
      { id: "sv-8-2", label: "Brosur A5 — Art Paper 210gr", price: 1500, attributes: { jenis: "brosur", ukuran: "A5", kertas: "art paper 210gr" }, sortOrder: 2 },
      { id: "sv-8-3", label: "Undangan 10×19 cm — Art Paper 230gr", price: 2500, attributes: { jenis: "undangan", ukuran: "10x19cm", kertas: "art paper 230gr" }, sortOrder: 3 },
      { id: "sv-8-4", label: "Kartu Nama — Art Paper 260gr (per 100 lembar)", price: 25000, attributes: { jenis: "kartu-nama", ukuran: "standar", batch: "100 lembar" }, sortOrder: 4 },
    ],
    useCases: [
      "Undangan nikah & syukuran",
      "Brosur promosi bisnis",
      "Kartu nama profesional",
      "Flyer event & seminar",
    ],
  },
];

// ============ PRODUK ATK ============
export const dummyProducts = [
  {
    id: "prod-1",
    categoryId: "cat-p1",
    categoryName: "Alat Tulis",
    categorySlug: "alat-tulis",
    name: "Pulpen Standard AE7 (Hitam)",
    slug: "pulpen-standard-ae7-hitam",
    description: "Pulpen Standard AE7 tinta hitam, ujung 0.7mm, anti bocor. Cocok untuk menulis sehari-hari, mengisi formulir, dan keperluan kantor. Kemasan satuan.",
    price: 3000,
    costPrice: 1800,
    stock: 48,
    lowStockThreshold: 10,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-2",
    categoryId: "cat-p2",
    categoryName: "Kertas & Buku",
    categorySlug: "kertas-buku",
    name: "Kertas HVS A4 70gr (Rim 500 lembar)",
    slug: "kertas-hvs-a4-70gr-rim",
    description: "Kertas HVS A4 70gr 1 rim (500 lembar), putih cerah, cocok untuk printer laser dan inkjet. Merk Sinar Dunia. Permukaan halus, tidak mudah kusut.",
    price: 55000,
    costPrice: 45000,
    stock: 12,
    lowStockThreshold: 5,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-3",
    categoryId: "cat-p2",
    categoryName: "Kertas & Buku",
    categorySlug: "kertas-buku",
    name: "Buku Tulis Sidu 38 Lembar",
    slug: "buku-tulis-sidu-38-lembar",
    description: "Buku tulis Sidu 38 lembar bergaris, cover tebal, kertas putih. Cocok untuk siswa SD, SMP, dan SMA. Dijual per buah.",
    price: 4000,
    costPrice: 2500,
    stock: 60,
    lowStockThreshold: 15,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-4",
    categoryId: "cat-p3",
    categoryName: "Amplop & Map",
    categorySlug: "amplop-map",
    name: "Amplop Cokelat Sedang (Ukuran 23×11 cm)",
    slug: "amplop-cokelat-sedang",
    description: "Amplop cokelat kraft ukuran sedang 23×11 cm, cocok untuk mengirim dokumen A4 terlipat. Tekstur kuat, lem berkualitas. Dijual per buah.",
    price: 500,
    costPrice: 250,
    stock: 100,
    lowStockThreshold: 20,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-5",
    categoryId: "cat-p3",
    categoryName: "Amplop & Map",
    categorySlug: "amplop-map",
    name: "Map Plastik Bening F4",
    slug: "map-plastik-bening-f4",
    description: "Map plastik transparan ukuran F4, dengan klip penjepit plastik yang kuat. Cocok untuk menyimpan dan mengarsipkan dokumen. Dijual per buah.",
    price: 2500,
    costPrice: 1200,
    stock: 30,
    lowStockThreshold: 8,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-6",
    categoryId: "cat-p1",
    categoryName: "Alat Tulis",
    categorySlug: "alat-tulis",
    name: "Pensil 2B Faber Castell",
    slug: "pensil-2b-faber-castell",
    description: "Pensil Faber Castell 2B, cocok untuk menggambar, membuat sketsa, dan mengisi lembar jawaban komputer (LJK). Mudah dihapus, tidak mudah patah.",
    price: 5000,
    costPrice: 3000,
    stock: 35,
    lowStockThreshold: 10,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-7",
    categoryId: "cat-p4",
    categoryName: "Tinta & Spidol",
    categorySlug: "tinta-spidol",
    name: "Spidol Permanent Snowman Hitam",
    slug: "spidol-permanent-snowman-hitam",
    description: "Spidol permanent Snowman tinta hitam, anti air setelah kering. Cocok untuk menulis di kertas, plastik, karton, dan berbagai permukaan.",
    price: 8000,
    costPrice: 5000,
    stock: 4,
    lowStockThreshold: 5,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-8",
    categoryId: "cat-p2",
    categoryName: "Kertas & Buku",
    categorySlug: "kertas-buku",
    name: "Kertas F4 HVS 70gr (Rim 500 lembar)",
    slug: "kertas-hvs-f4-70gr-rim",
    description: "Kertas HVS F4 70gr 1 rim (500 lembar), ukuran 21×33 cm. Cocok untuk dokumen legal dan formulir. Merk Sinar Dunia.",
    price: 65000,
    costPrice: 53000,
    stock: 8,
    lowStockThreshold: 5,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-9",
    categoryId: "cat-p1",
    categoryName: "Alat Tulis",
    categorySlug: "alat-tulis",
    name: "Penggaris 30 cm Joyko",
    slug: "penggaris-30cm-joyko",
    description: "Penggaris plastik 30 cm merk Joyko, transparan dengan skala mm yang jelas. Kuat dan tidak mudah melengkung.",
    price: 5000,
    costPrice: 2500,
    stock: 22,
    lowStockThreshold: 5,
    imageUrl: null,
    isActive: true,
  },
  {
    id: "prod-10",
    categoryId: "cat-p3",
    categoryName: "Amplop & Map",
    categorySlug: "amplop-map",
    name: "Amplop Putih Kecil A6 (isi 10)",
    slug: "amplop-putih-kecil-a6",
    description: "Amplop putih ukuran A6 untuk undangan dan surat kecil. Isi 10 lembar per bungkus, dengan lem perekat.",
    price: 5000,
    costPrice: 3000,
    stock: 0,
    lowStockThreshold: 5,
    imageUrl: null,
    isActive: true,
  },
];


// ============ SETTINGS TOKO ============
export const dummySettings = {
  store_name: "Dinar Fotocopy",
  store_tagline: "Cetak cepat, rapi, dan terpercaya sejak 2015.",
  store_address: "Jl. Melati No. 22, Kel. Sukamaju, Kota Bandung",
  store_whatsapp: "628123456789",
  store_operational_hours: "Senin–Sabtu 08.00–21.00 WIB, Minggu 09.00–17.00 WIB",
  map_embed_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.8044444444446!2d107.6189!3d-6.9175!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNsKwNTUnMDMuMCJTIDEwN8KwMzcnMDguMCJF!5e0!3m2!1sid!2sid!4v1700000000000!5m2!1sid!2sid",
  bulk_discount_rules: [
    { minQty: 100, percent: 5 },
    { minQty: 500, percent: 10 },
  ],
  notify_admin_on_new_order: true,
};

// ============ TESTIMONI ============
export const dummyTestimonials = [
  {
    id: "t-1",
    name: "Budi Santoso",
    role: "Mahasiswa Teknik",
    content: "Cetak skripsi 200 lembar plus jilid hardcover selesai dalam 2 jam. Hasilnya rapi dan harganya wajar. Recommended banget!",
    rating: 5,
  },
  {
    id: "t-2",
    name: "Ibu Ratna",
    role: "Guru SD Negeri 1",
    content: "Sudah 3 tahun fotokopi soal ujian di sini. Selalu cepat, harga bersahabat, dan staf-nya ramah. Tidak pernah kecewa.",
    rating: 5,
  },
  {
    id: "t-3",
    name: "Dimas Prayoga",
    role: "Pemilik Toko Online",
    content: "Print banner untuk grand opening toko saya di sini. Warna cerah, bahan tebal, dan selesai tepat waktu. Puas sekali!",
    rating: 5,
  },
];

// ============ FAQ ============
export const dummyFaq = [
  {
    id: "faq-1",
    question: "Bagaimana cara mengirim file untuk dicetak?",
    answer: "Anda bisa mengirim file via WhatsApp ke nomor kami (0812-3456-789), email ke dinar@fotocopy.id, atau langsung bawa flash disk/hardisk ke toko. Format yang didukung: PDF, DOCX, XLSX, PPTX, JPG, PNG, dan CDR.",
  },
  {
    id: "faq-2",
    question: "Berapa lama waktu pengerjaan pesanan?",
    answer: "Print & fotokopi biasanya selesai dalam 30–60 menit. Cetak foto 1–2 jam. Jilid spiral 30 menit. Cetak banner 1–3 hari kerja tergantung ukuran. Kami konfirmasi estimasi waktu setelah file diterima.",
  },
  {
    id: "faq-3",
    question: "Apakah ada layanan antar untuk pesanan banner?",
    answer: "Saat ini kami belum menyediakan layanan antar. Semua pesanan diambil langsung di toko kami di Jl. Melati No. 22, Bandung. Namun untuk order dalam jumlah besar, silakan hubungi kami untuk diskusi lebih lanjut.",
  },
  {
    id: "faq-4",
    question: "Apakah harga yang tertera sudah termasuk biaya desain?",
    answer: "Harga yang tertera adalah harga cetak saja. Jika Anda membutuhkan jasa desain (banner, undangan, brosur), ada biaya tambahan mulai dari Rp 50.000 tergantung kompleksitas. Hubungi kami untuk info lebih lanjut.",
  },
  {
    id: "faq-5",
    question: "Apakah bisa fotokopi atau print dalam jumlah banyak?",
    answer: "Bisa! Kami siap melayani pesanan dalam jumlah besar. Bahkan, ada diskon otomatis: fotokopi/print ≥100 lembar diskon 5%, ≥500 lembar diskon 10%.",
  },
  {
    id: "faq-6",
    question: "Format pembayaran apa saja yang diterima?",
    answer: "Kami menerima pembayaran tunai dan transfer bank (BCA, BRI, BNI, Mandiri). Pembayaran dilakukan langsung di toko saat mengambil pesanan.",
  },
  {
    id: "faq-7",
    question: "Jam buka toko Dinar Fotocopy?",
    answer: "Kami buka Senin–Sabtu pukul 08.00–21.00 WIB dan Minggu pukul 09.00–17.00 WIB. Kami tutup di hari libur nasional.",
  },
  {
    id: "faq-8",
    question: "Bagaimana cara melacak status pesanan saya?",
    answer: "Setelah memesan, Anda akan mendapat kode unik pesanan (contoh: DF-250120-0001). Kami akan mengirim notifikasi WhatsApp setiap kali status pesanan berubah. Anda juga bisa menghubungi kami langsung via WhatsApp.",
  },
  {
    id: "faq-9",
    question: "Apakah bisa cetak dari HP langsung?",
    answer: "Bisa! Kirimkan file via WhatsApp, atau buka file di HP Anda dan tunjukkan ke staf kami. Kami akan membantu transfer file dengan cepat.",
  },
  {
    id: "faq-10",
    question: "Apakah produk ATK bisa dipesan tanpa cetak?",
    answer: "Tentu! Katalog ATK kami tersedia untuk dibeli secara terpisah. Cukup tambahkan produk ke keranjang estimasi dan lakukan pemesanan via WhatsApp.",
  },
];

// ============ ORDERS ============
export const dummyOrders = [
  {
    id: "ord-1",
    code: "DF-250120-0001",
    customerName: "Budi Santoso",
    customerWhatsapp: "628112345678",
    customerNote: "Mohon print bolak-balik untuk menghemat kertas.",
    pickupMethod: "pickup",
    status: "completed",
    totalEstimate: 67500,
    adminNote: "File sudah diterima via WA.",
    createdAt: new Date("2025-01-20T09:15:00+07:00"),
    updatedAt: new Date("2025-01-20T14:30:00+07:00"),
    items: [
      { id: "oi-1-1", itemType: "service", itemName: "Fotokopi Dokumen", variantLabel: "A4 HVS 70gr — Hitam Putih", quantity: 150, unitPrice: 300, discountPercent: 5, subtotal: 42750 },
      { id: "oi-1-2", itemType: "service", itemName: "Jilid Spiral", variantLabel: "A4 Spiral Warna", quantity: 1, unitPrice: 7500, discountPercent: 0, subtotal: 7500 },
      { id: "oi-1-3", itemType: "product", itemName: "Pulpen Standard AE7", variantLabel: null, quantity: 6, unitPrice: 3000, discountPercent: 0, subtotal: 18000 },
    ],
    statusLogs: [
      { id: "sl-1-1", fromStatus: null, toStatus: "pending", note: "Pesanan masuk via website", createdAt: new Date("2025-01-20T09:15:00+07:00") },
      { id: "sl-1-2", fromStatus: "pending", toStatus: "confirmed", note: "Admin konfirmasi file diterima", createdAt: new Date("2025-01-20T09:40:00+07:00") },
      { id: "sl-1-3", fromStatus: "confirmed", toStatus: "in_progress", note: "Mulai cetak", createdAt: new Date("2025-01-20T10:00:00+07:00") },
      { id: "sl-1-4", fromStatus: "in_progress", toStatus: "ready", note: "Selesai, siap diambil", createdAt: new Date("2025-01-20T11:30:00+07:00") },
      { id: "sl-1-5", fromStatus: "ready", toStatus: "completed", note: "Pesanan diambil oleh pelanggan", createdAt: new Date("2025-01-20T14:30:00+07:00") },
    ],
  },
  {
    id: "ord-2",
    code: "DF-250121-0002",
    customerName: "Siti Rahayu",
    customerWhatsapp: "628122334455",
    customerNote: "Banner untuk acara pernikahan, mohon warna cerah.",
    pickupMethod: "pickup",
    status: "in_progress",
    totalEstimate: 120000,
    adminNote: "",
    createdAt: new Date("2025-01-21T10:00:00+07:00"),
    updatedAt: new Date("2025-01-21T11:00:00+07:00"),
    items: [
      { id: "oi-2-1", itemType: "service", itemName: "Cetak Banner Flexi", variantLabel: "Flexi Indoor 340gsm — 3×1 m", quantity: 3, unitPrice: 35000, discountPercent: 0, subtotal: 105000 },
      { id: "oi-2-2", itemType: "service", itemName: "Laminating", variantLabel: "A4 Glossy", quantity: 5, unitPrice: 3000, discountPercent: 0, subtotal: 15000 },
    ],
    statusLogs: [
      { id: "sl-2-1", fromStatus: null, toStatus: "pending", note: "Pesanan masuk via website", createdAt: new Date("2025-01-21T10:00:00+07:00") },
      { id: "sl-2-2", fromStatus: "pending", toStatus: "confirmed", note: "File desain diterima", createdAt: new Date("2025-01-21T10:30:00+07:00") },
      { id: "sl-2-3", fromStatus: "confirmed", toStatus: "in_progress", note: "Proses cetak dimulai", createdAt: new Date("2025-01-21T11:00:00+07:00") },
    ],
  },
  {
    id: "ord-3",
    code: "DF-250121-0003",
    customerName: "Ahmad Fauzi",
    customerWhatsapp: "628133445566",
    customerNote: "",
    pickupMethod: "pickup",
    status: "pending",
    totalEstimate: 45000,
    adminNote: "",
    createdAt: new Date("2025-01-21T14:20:00+07:00"),
    updatedAt: new Date("2025-01-21T14:20:00+07:00"),
    items: [
      { id: "oi-3-1", itemType: "service", itemName: "Print Dokumen", variantLabel: "A4 — Berwarna (Laser)", quantity: 30, unitPrice: 1500, discountPercent: 0, subtotal: 45000 },
    ],
    statusLogs: [
      { id: "sl-3-1", fromStatus: null, toStatus: "pending", note: "Pesanan masuk via website", createdAt: new Date("2025-01-21T14:20:00+07:00") },
    ],
  },
  {
    id: "ord-4",
    code: "DF-250122-0004",
    customerName: "Dewi Pertiwi",
    customerWhatsapp: "628144556677",
    customerNote: "Jilid hardcover warna merah untuk skripsi.",
    pickupMethod: "pickup",
    status: "ready",
    totalEstimate: 95000,
    adminNote: "Hardcover selesai, tinggal finishing.",
    createdAt: new Date("2025-01-22T08:30:00+07:00"),
    updatedAt: new Date("2025-01-22T12:00:00+07:00"),
    items: [
      { id: "oi-4-1", itemType: "service", itemName: "Fotokopi Dokumen", variantLabel: "A4 HVS 70gr — Hitam Putih", quantity: 200, unitPrice: 300, discountPercent: 5, subtotal: 57000 },
      { id: "oi-4-2", itemType: "service", itemName: "Jilid Hardcover", variantLabel: "Hardcover Warna — A4", quantity: 1, unitPrice: 38000, discountPercent: 0, subtotal: 38000 },
    ],
    statusLogs: [
      { id: "sl-4-1", fromStatus: null, toStatus: "pending", note: "Pesanan masuk via website", createdAt: new Date("2025-01-22T08:30:00+07:00") },
      { id: "sl-4-2", fromStatus: "pending", toStatus: "confirmed", note: "File skripsi diterima", createdAt: new Date("2025-01-22T09:00:00+07:00") },
      { id: "sl-4-3", fromStatus: "confirmed", toStatus: "in_progress", note: "Mulai cetak dan jilid", createdAt: new Date("2025-01-22T09:30:00+07:00") },
      { id: "sl-4-4", fromStatus: "in_progress", toStatus: "ready", note: "Skripsi siap diambil", createdAt: new Date("2025-01-22T12:00:00+07:00") },
    ],
  },
  {
    id: "ord-5",
    code: "DF-250122-0005",
    customerName: "Lina Marlina",
    customerWhatsapp: "628144555666",
    customerNote: "Cetak foto 4R untuk wisuda.",
    pickupMethod: "pickup",
    status: "completed",
    totalEstimate: 35000,
    adminNote: "",
    createdAt: new Date("2025-01-22T11:00:00+07:00"),
    updatedAt: new Date("2025-01-22T13:30:00+07:00"),
    items: [
      { id: "oi-5-1", itemType: "service", itemName: "Cetak Foto", variantLabel: "4R (10×15 cm) — Glossy", quantity: 14, unitPrice: 2500, discountPercent: 0, subtotal: 35000 },
    ],
    statusLogs: [
      { id: "sl-5-1", fromStatus: null, toStatus: "pending", note: "Pesanan masuk via website", createdAt: new Date("2025-01-22T11:00:00+07:00") },
      { id: "sl-5-2", fromStatus: "pending", toStatus: "confirmed", note: "File foto diterima", createdAt: new Date("2025-01-22T11:15:00+07:00") },
      { id: "sl-5-3", fromStatus: "confirmed", toStatus: "in_progress", note: "Proses cetak foto", createdAt: new Date("2025-01-22T11:30:00+07:00") },
      { id: "sl-5-4", fromStatus: "in_progress", toStatus: "ready", note: "Foto siap diambil", createdAt: new Date("2025-01-22T13:00:00+07:00") },
      { id: "sl-5-5", fromStatus: "ready", toStatus: "completed", note: "Diambil pelanggan", createdAt: new Date("2025-01-22T13:30:00+07:00") },
    ],
  },
];

// ============ NOTIFICATIONS ============
export const dummyNotifications = [
  {
    id: "notif-1",
    orderId: "ord-1",
    orderCode: "DF-250120-0001",
    channel: "whatsapp",
    provider: "fonnte",
    targetNumber: "628112345678",
    targetName: "Budi Santoso",
    templateKey: "order_confirmed_customer",
    messageBody: "Halo Budi Santoso! Pesanan Anda DF-250120-0001 sudah dikonfirmasi. Kami segera memproses pesanan Anda. Terima kasih telah memesan di Dinar Fotocopy 🙏.",
    status: "sent",
    providerMessageId: "fonnte-msg-abc123",
    retryCount: 0,
    sentAt: new Date("2025-01-20T09:40:30+07:00"),
    createdAt: new Date("2025-01-20T09:40:00+07:00"),
  },
  {
    id: "notif-2",
    orderId: "ord-1",
    orderCode: "DF-250120-0001",
    channel: "whatsapp",
    provider: "fonnte",
    targetNumber: "628112345678",
    targetName: "Budi Santoso",
    templateKey: "status_ready_customer",
    messageBody: "Kabar baik! Pesanan DF-250120-0001 sudah siap diambil di Dinar Fotocopy. Total Rp 67.500. Terima kasih 🙏.",
    status: "sent",
    providerMessageId: "fonnte-msg-def456",
    retryCount: 0,
    sentAt: new Date("2025-01-20T11:30:30+07:00"),
    createdAt: new Date("2025-01-20T11:30:00+07:00"),
  },
  {
    id: "notif-3",
    orderId: "ord-2",
    orderCode: "DF-250121-0002",
    channel: "whatsapp",
    provider: "fonnte",
    targetNumber: "628122334455",
    targetName: "Siti Rahayu",
    templateKey: "order_confirmed_customer",
    messageBody: "Halo Siti Rahayu! Pesanan banner Anda DF-250121-0002 sudah dikonfirmasi. Estimasi selesai 2–3 hari kerja. Kami hubungi via WA jika sudah siap 🙏.",
    status: "sent",
    providerMessageId: "fonnte-msg-ghi789",
    retryCount: 0,
    sentAt: new Date("2025-01-21T10:30:30+07:00"),
    createdAt: new Date("2025-01-21T10:30:00+07:00"),
  },
  {
    id: "notif-4",
    orderId: "ord-3",
    orderCode: "DF-250121-0003",
    channel: "whatsapp",
    provider: "fonnte",
    targetNumber: "628133445566",
    targetName: "Ahmad Fauzi",
    templateKey: "order_received_customer",
    messageBody: "Terima kasih Ahmad Fauzi! Pesanan Anda DF-250121-0003 sudah kami terima. Kami akan segera konfirmasi dalam beberapa menit. Dinar Fotocopy 🙏.",
    status: "failed",
    providerMessageId: null,
    retryCount: 2,
    sentAt: null,
    createdAt: new Date("2025-01-21T14:20:30+07:00"),
  },
  {
    id: "notif-5",
    orderId: "ord-5",
    orderCode: "DF-250122-0005",
    channel: "whatsapp",
    provider: "fonnte",
    targetNumber: "628144555666",
    targetName: "Lina Marlina",
    templateKey: "status_ready_customer",
    messageBody: "Kabar baik! Pesanan DF-250122-0005 sudah siap diambil di Dinar Fotocopy. Total Rp 35.000. Terima kasih 🙏.",
    status: "sent",
    providerMessageId: "fonnte-msg-jkl012",
    retryCount: 0,
    sentAt: new Date("2025-01-22T13:00:05+07:00"),
    createdAt: new Date("2025-01-22T13:00:00+07:00"),
  },
];

// ============ DASHBOARD STATS ============
export const dummyDashboardStats = {
  ordersToday: 5,
  ordersPending: 2,
  lowStockProducts: 2,
  completedThisWeek: 18,
  chartData: [
    { day: "Sen", orders: 4 },
    { day: "Sel", orders: 7 },
    { day: "Rab", orders: 5 },
    { day: "Kam", orders: 9 },
    { day: "Jum", orders: 12 },
    { day: "Sab", orders: 8 },
    { day: "Min", orders: 3 },
  ],
};

// ============ ORDER STATUS LABELS ============
export const orderStatusConfig = {
  draft: { label: "Draft", className: "badge-draft" },
  pending: { label: "Menunggu", className: "badge-pending" },
  confirmed: { label: "Dikonfirmasi", className: "badge-confirmed" },
  in_progress: { label: "Dikerjakan", className: "badge-in-progress" },
  ready: { label: "Siap Ambil", className: "badge-ready" },
  completed: { label: "Selesai", className: "badge-completed" },
  cancelled: { label: "Dibatalkan", className: "badge-cancelled" },
} as const;

export type OrderStatus = keyof typeof orderStatusConfig;
